name: 'Build and tag docker image'
description: 'Build and tag docker image'
branding:
  color: 'blue'
  icon: 'arrow-down-circle'
inputs:
  tag:
    description: version of docker image
    required: true
runs:
  using: 'composite'
  steps:
    - name: build and tag
      shell: bash
      run: pack build ${{ github.event.repository.name }}:${{ inputs.tag }} --path . --builder heroku/builder:20
